import type { Metadata } from "next";
import "./globals.css";
import ReownAppkitProvider from "@/providers/reown/reown.provider";
import Header from "@/components/ui/header";
import { ReactQueryProvider } from "@/providers/tanstack/tanstack.provider";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body className={`antialiased`}>
				<ReactQueryProvider>
					<ReownAppkitProvider>
						<div className='flex flex-col h-screen'>
							<Header />
							{children}
						</div>
					</ReownAppkitProvider>
				</ReactQueryProvider>
			</body>
		</html>
	);
}
